hyperthreads_executor: false
num_executors: 512
num_executor_cores: 8
num_general_cores: 4

affinity_mode: unfixed
policy: blocking
sys_metrics_freq: 1s

warmup:
  rps: 5000
  time: 10s

measure:
  start_rps: 8000
  final_rps: 13000
  steps: 5
  step_time: 5s
