num_executors: 16
num_executor_cores: 16
num_general_cores: 4

affinity_mode: fixed
policy: cooperative

sys_metrics_freq: 1s

warmup:
  time: 10s
  rps: 100

measure:
  start_rps: 100
  final_rps: 300
  steps: 5
  step_time: 5s

script_path: ./scripts/test-1.js
